[project]
name = "time-tracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flet[all]>=0.80.0",
    "markdown>=3.10",
    "peewee>=3.18.3",
    "psutil>=7.2.0",
    "pywinctl>=0.4.1",
]

[dependency-groups]
dev = [
    "ty>=0.0.8",
]
